/*
 free to use, free to change, anything you can do
*/
(function(e){function n(a){return".css"==a.slice(-4).toLowerCase()||0<a.toLowerCase().indexOf(".css?")?!0:!1}function q(a){var c=a.indexOf("://");if(0>c)return!1;var b=a.indexOf("/",c+3);0<b&&(c=a.substring(0,b));c=location.href.toLowerCase().indexOf(c.toLowerCase());return-1<c&&6>c?!1:!0}function l(){var a,c;c=!1;for(a in d)0!==d[a]||q(a)||(d[a]=2,r(a));for(a in d)if(isNaN(d[a]))p[a]=1,c=d[a],delete d[a],t(a,c);else{if(2===d[a]&&config.sequence||0===d[a]&&(d[a]=2,q(a)?u(a):r(a),config.sequence))return e.setTimeout(l,
config.frequency);if(1===d[a]||0>d[a])p[a]=d[a],delete d[a]}c=!1;for(a in d){c=!0;break}if(c)return e.setTimeout(l,config.frequency);for(m=!1;a=callback.pop();)a.call(e)}function r(a){var c=a,b;a:{try{b=new e.XMLHttpRequest;break a}catch(f){}try{b=new e.ActiveXObject("Microsoft.XMLHTTP");break a}catch(g){}throw new Exception("cant use ajax");}b.onreadystatechange=function(){if(4==b.readyState)if(200==b.status)d[a]="string"==typeof b.responseText?b.responseText:-1;else{d[a]=-b.status;var c="using failed: "+
a+" got status: "+b.status;"string"==typeof b.responseText&&(c+=" and detail:\n"+b.responseText);e.console&&e.console.log(c)}};0>c.indexOf("/")&&config.basepath&&(c=config.basepath+c);b.open("GET",c);b.setRequestHeader("X-Requested-With","XMLHttpRequest");b.send();s(a)}function u(a){var c=n(a),b=g.createElement(c?"link":"script");b.onload=b.onreadystatechange=function(){this.readyState&&"loaded"!=this.readyState&&"complete"!=this.readyState||(d[a]=1,b.onload=b.onreadystatechange=null)};c?(b.href=
a,b.rel="stylesheet",b.type="text/css"):(b.src=a,b.type="text/javascript");b.id="_vspace_"+Math.random();g.body.appendChild(b);s(a)}function s(a){e.setTimeout(function(){"undefined"!=typeof d[a]&&2==d[a]&&(d[a]=-2,e.console&&e.console.log("timeout: "+a))},config.timeout)}function t(a,c){if(n(a))if(v){var b="_vspacecss_"+Math.random();e[b]=c;g.createStyleSheet("javascript:window['"+b+"'];")}else{var b=g.createElement("style"),d=g.head||g.getElementsByTagName("head")[0];b.type="text/css";b.textContent?
b.textContent=c:b.styleSheet?b.styleSheet.cssText=c:b.innerHTML=c;d.appendChild(b)}else eval.call(e,c)}var g=e.document,v=!!e.ActiveXObject&&!e.XMLHttpRequest,d={},p={},m=!1;callback=[];config={sequence:!0,frequency:50,timeout:3E3,basepath:""};e.namespace=function(a){if(!a||!a.length)return null;a=a.split(".");var c=e,b;for(b="window"==a[0]?1:0;b<a.length;++b)c[a[b]]=c[a[b]]||{},c=c[a[b]];return c};e.using=function(){for(var a=0;a<arguments.length;a++){var c=(arguments[a]||"").replace(/^\s+|\s+$/g,
"");"undefined"!=typeof d[c]||"undefined"!=typeof p[c]&&!n(c)||(d[c]=0)}m||(m=!0,l());return e.using};e.using.ready=function(a){callback.push(a);m||(m=!0,l())};e.using.config=function(a,c){if("undefined"==typeof a)return config;if("object"!=typeof a){var b={};b[a]=c;a=b}for(b in a)"string"==typeof a[b]&&("true"==a[b].toLowerCase()?a[b]=!0:"false"==a[b].toLowerCase()&&(a[b]=!1)),config[b]=a[b]};var f,h,k=g.getElementsByTagName("script");for(h in k)if(k[h].src&&-1<k[h].src.indexOf("vspace")){for(f in config)k[h].getAttribute(f)&&
using.config(f,k[h].getAttribute(f));if(f=k[h].getAttribute("run"))f=1>f.indexOf(",")?[f]:f.split(","),using.apply(e,f);break}delete f;delete h;delete k})(window);
