/*
 free to use, free to change, anything you can do
*/
(function(d){function n(a){return".css"==a.slice(-4).toLowerCase()||0<a.toLowerCase().indexOf(".css?")?!0:!1}function q(a){var c=a.indexOf("://");if(0>c)return!1;var b=a.indexOf("/",c+3);0<b&&(c=a.substring(0,b));c=location.href.toLowerCase().indexOf(c.toLowerCase());return-1<c&&6>c?!1:!0}function l(){var a,c;for(a in e)0!==e[a]||q(a)||(e[a]=2,r(a));for(a in e)if(isNaN(e[a]))p[a]=1,c=e[a],delete e[a],t(a,c);else{if(2===e[a]&&config.sequence||0===e[a]&&(e[a]=2,q(a)?u(a):r(a),config.sequence))return d.setTimeout(l,
config.frequency);if(1===e[a]||0>e[a])p[a]=e[a],delete e[a]}for(a in e)return d.setTimeout(l,config.frequency);for(m=!1;a=callback.pop();)a.call(d)}function r(a){var c=a,b;a:{try{b=new d.XMLHttpRequest;break a}catch(f){}try{b=new d.ActiveXObject("Microsoft.XMLHTTP");break a}catch(g){}throw new Exception("cant use ajax");}b.onreadystatechange=function(){if(4==b.readyState)if(200==b.status)e[a]="string"==typeof b.responseText?b.responseText:-1;else{e[a]=0==b.status?-404:-b.status;var c="using failed: "+
a+" got status: "+b.status;"string"==typeof b.responseText&&(c+=" and detail:\n"+b.responseText);d.console&&d.console.log(c)}};0>c.indexOf("/")&&config.basepath&&(c=config.basepath+c);b.open("GET",c);b.setRequestHeader("X-Requested-With","XMLHttpRequest");b.send();s(a)}function u(a){var c=n(a),b=g.createElement(c?"link":"script");b.onload=b.onreadystatechange=function(){this.readyState&&"loaded"!=this.readyState&&"complete"!=this.readyState||(e[a]=1,b.onload=b.onreadystatechange=null)};c?(b.href=
a,b.rel="stylesheet",b.type="text/css"):(b.src=a,b.type="text/javascript");b.id="_vspace_"+parseInt(1E7*Math.random());g.body.appendChild(b);s(a)}function s(a){d.setTimeout(function(){"undefined"!=typeof e[a]&&2==e[a]&&(e[a]=-2,d.console&&d.console.log("timeout: "+a))},config.timeout)}function t(a,c){if(n(a))if(v){var b="_vspacecss_"+Math.random();d[b]=c;g.createStyleSheet("javascript:window['"+b+"'];")}else{var b=g.createElement("style"),e=g.head||g.getElementsByTagName("head")[0];b.type="text/css";
b.textContent?b.textContent=c:b.styleSheet?b.styleSheet.cssText=c:b.innerHTML=c;e.appendChild(b)}else eval.call(d,c)}var g=d.document,v=!!d.ActiveXObject&&!d.XMLHttpRequest,e={},p={},m=!1;callback=[];config={sequence:!0,frequency:50,timeout:3E3,basepath:""};d.namespace=function(a){if(!a||!a.length)return null;a=a.split(".");var c=d,b;for(b="window"==a[0]?1:0;b<a.length;++b)c[a[b]]=c[a[b]]||{},c=c[a[b]];return c};d.using=function(){if(1==arguments.length&&"function"==typeof arguments[0])return d.using.ready(arguments[0]),
d.using;for(var a=0;a<arguments.length;a++){var c=(arguments[a]||"").replace(/^\s+|\s+$/g,"");"undefined"!=typeof e[c]||"undefined"!=typeof p[c]&&!n(c)||(e[c]=0)}m||(m=!0,l());return d.using};d.using.ready=function(a){d.setTimeout(function(){callback.push(a);m||(m=!0,l())},config.frequency>>1)};d.using.config=function(a,c){if("undefined"==typeof a)return config;if("object"!=typeof a){var b={};b[a]=c;a=b}for(b in a)"string"==typeof a[b]&&("true"==a[b].toLowerCase()?a[b]=!0:"false"==a[b].toLowerCase()&&
(a[b]=!1)),config[b]=a[b]};var f,h,k=g.getElementsByTagName("script");for(h in k)if(k[h].src&&-1<k[h].src.indexOf("vspace")){for(f in config)k[h].getAttribute(f)&&using.config(f,k[h].getAttribute(f));if(f=k[h].getAttribute("run"))f=1>f.indexOf(",")?[f]:f.split(","),using.apply(d,f);break}delete f;delete h;delete k})(window);
